-- 创建数据库
CREATE DATABASE IF NOT EXISTS campus_carbon DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 使用数据库
USE campus_carbon;

-- 创建学生表
CREATE TABLE IF NOT EXISTS student (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    stu_no VARCHAR(20) NOT NULL UNIQUE COMMENT '学号',
    name VARCHAR(50) NOT NULL COMMENT '姓名',
    openid VARCHAR(100) NOT NULL UNIQUE COMMENT '小程序唯一标识',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学生表';

-- 创建步数统计表
CREATE TABLE IF NOT EXISTS step_count (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    student_id BIGINT NOT NULL COMMENT '关联学生ID',
    date DATE NOT NULL COMMENT '统计日期',
    step_num INT NOT NULL COMMENT '步数',
    calorie DOUBLE NOT NULL COMMENT '卡路里',
    duration INT NOT NULL COMMENT '运动时长(分钟)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_student_date (student_id, date),
    FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='步数统计表';

-- 创建运动记录表
CREATE TABLE IF NOT EXISTS sport_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    student_id BIGINT NOT NULL COMMENT '关联学生ID',
    sport_type VARCHAR(50) NOT NULL COMMENT '运动类型(走路/跑步/骑行)',
    start_time DATETIME NOT NULL COMMENT '开始时间',
    end_time DATETIME NOT NULL COMMENT '结束时间',
    distance DOUBLE NOT NULL COMMENT '距离',
    calorie DOUBLE NOT NULL COMMENT '消耗',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运动记录表';

-- 创建AI建议表
CREATE TABLE IF NOT EXISTS ai_suggest (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    student_id BIGINT NOT NULL COMMENT '关联学生ID',
    input_text TEXT NOT NULL COMMENT '用户输入的碳足迹',
    suggest_text TEXT NOT NULL COMMENT '百炼AI返回的建议',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI建议表';